"""username(unique=True) -> username(unique=False)

Revision ID: 0f0f135ca572
Revises: 6369a0f9dbfb
Create Date: 2023-07-30 16:20:15.941520

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "0f0f135ca572"
down_revision = "6369a0f9dbfb"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("users_username_key", "users", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("users_username_key", "users", ["username"])
    # ### end Alembic commands ###
