"""add surname field

Revision ID: fae222b6848e
Revises: 0f0f135ca572
Create Date: 2023-07-30 18:43:31.776176

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "fae222b6848e"
down_revision = "0f0f135ca572"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("surname", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "surname")
    # ### end Alembic commands ###
